### ISSUE TITLE
Missing mapping for touchpad button - PS4 controller

### ISSUE THREAD

**Issue by DrRevert** [mdqinc/SDL_GameControllerDB#520]
Almost all the entries for PS4 (except those for MacOS) are missing binding for touchpad button, even though that button is recognized by the operating system and should be recognized by SDL according to source code.

I checked in Godot Engine (which uses the SDL_GameControllerDB, but not SDL on its own, so not sure if results will be the same) that adding `touchpad:b13` to the mapping of PS4 controller worked in my case on Windows.

Seems to be quite a glaring omission, which could be caused by all the mapping tools mentioned in readme not supporting all the possible buttons.

**Comment by offalynne** [comment]
The `touchpad` field was a later addition to the mapping spec and SDL is manually adding the by controller type per-platform. I suggest taking this downstream to Gadot. I'm open to per-GUID PRs to add the field, but I'd rather not diverge from SDL's approach if the value is the same as the one SDL sets automatically.

**Comment by DrRevert** [comment]
I disagree with fixing the issue only on Godot side, it seems to me that the issue is global, so I reported the issue in the SDL github https://github.com/libsdl-org/SDL/issues/5035 
As for providing per-GUID PR, I can only be sure that the mapping is correct for 030000004c050000cc09000000016800 but there seems to be more PS4 Controllers whoch should also be fixed.

**Comment by offalynne** [comment]
Click the link and read the quoted source.
