### ISSUE TITLE
Admin migration

### ISSUE THREAD

**Issue by offalynne** [mdqinc/SDL_GameControllerDB#720]
@gabomdq would you be willing to transfer me repository ownership ?

Reasons I'm asking:
- Since I started comaintaining 3 years ago after a particular incident involving another party, [I have been managing PRs and issues solo](https://github.com/gabomdq/SDL_GameControllerDB/graphs/contributors)
- Having elevated access to settings for Workflow configuration etc. would be helpful for maintenance
- I have been in communication with upstream maintainers of projects including SDL, Godot, GameMaker, Moonlight, etc. where this repo has impact when the need has arisen
- I have advocated for the project outside the purview of SDL specifically in other places where related data is handled and gathered, where decisions or contributions have impacted this repo (Linux udev projects, Steam Input, Libretro, etc.) 
- I believe GH automatically handles all redirects without complication upon ownership transference so this should not cause any issues for projects relying on this repo
- In the (for now unforseen) event that I am no longer able to maintain the repo some time in the future, I would like to have rights access to designate another maintainer to pass the reigns

*Not* reasons I'm asking:
- I am not seeking elevated credit for the contents of the repo as it is, and should remain, a community effort maintained and distributed under SDL's upstream license
- I am not seeking to diminish your involvement with the repo, from its creation through to handling many isuses and PRs in years past

In the event you want to go through with this, I commit to keeping the repo and it's contents in the order it has been years prior, without any change to license or presentation.

I am making this a public issue instead of messaging you privately because I suspect it might be a touchy subject after The Events that occurred prior to my original user-rights elevation in 2020: if you or anyone else with eyes here does not wish for this change or sees an issue with it that I have missed, I am glad to drop the issue, but figured I would ask. :-)

Thanks for your time !

**Comment by gabomdq** [comment]
I converted the repo to be org owned and added you as full admin. Thanks a lot for your work!

**Comment by offalynne** [comment]
Thank you :)
