### ISSUE TITLE
after closing a game, sdl error

### ISSUE THREAD

**Issue by Niieene** [mdqinc/SDL_GameControllerDB#739]
hi,
controler works, but after closing:
After closing game and going to Gamepad settings, SDL no longer locates the controller and throws E SDL: Could not open device 0! SDL Error: IDirectInputDevice8::SetCooperativeLevel() DirectX error 0x80070006 x4

[RPCS3.log](https://github.com/mdqinc/SDL_GameControllerDB/files/14373623/RPCS3.log)

**Comment by offalynne** [comment]
Report this to RPCS3
