### ISSUE TITLE
add missing controller support

### ISSUE THREAD

**Issue by Lothar635** [mdqinc/SDL_GameControllerDB#777]
universal usb convertor by gamemon

03000000fa190000918d000000000000,3 In 1 Conversion Box,a:b2,b:b1,back:b9,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,leftshoulder:b6,leftstick:b10,lefttrigger:b4,leftx:a0,lefty:a1,rightshoulder:b7,rightstick:b11,righttrigger:b5,rightx:a3,righty:a2,start:b8,x:b3,y:b0,platform:Windows,

this seems to be a variant of 3 In 1 Conversion Box

**Comment by offalynne** [comment]
327f2e953ac33d3c211272aeb4dc2a582bfbc5e1
