### ISSUE TITLE
How can I add a new mapping in this repo?

### ISSUE THREAD

**Issue by bomb2777** [mdqinc/SDL_GameControllerDB#782]
Hi, I want to add 2 mappings for "Alfadata USB Gameport Adaptor" for Linux and Windows. 

`030000009d0700000102000000010000,Alfadata USB Gameport Adaptor,a:b1,x:b0,dpup:a1,dpleft:a0,platform:Linux,`
`030000009d0700000102000000000000,Alfadata USB Gameport Adaptor,a:b1,x:b0,dpup:a1,dpleft:a0,platform:Windows,`

How is this handled in this repo? I have no permission to push a branch (and thus, I can not open a PR).
Thank you in advance for your answer!

Best regards, Max

**Comment by offalynne** [comment]
> *I can not open a PR*
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

> *Hi, I want to add 2 mappings*
With respect, why? The mapping has 2 buttons and 2 axes. A mapping is surely unnecessary for SDL in this case.

**Comment by bomb2777** [comment]
Thank you for your answer. I totally forgot about the Github UI, didn't use that for ages... sorry for that question.

To answer your question: it is a simple controller with 2 and 2 buttons, the mapping is for following:
![image](https://github.com/user-attachments/assets/ca3572df-5a1e-4d74-aa39-dd207a8243aa)

You also could connect Joysticks with only 1 Firebutton (e.g. think of old Amiga controllers).
I am developing a game with libgdx, and it just does not see this device whilst it sees other connected Gamepads e.g. Logitech Gamepad F310 which has a mapping in [gamecontrollerdb.txt](https://github.com/mdqinc/SDL_GameControllerDB/blob/master/gamecontrollerdb.txt).
