### ISSUE TITLE
Could you add explanation for fields?

### ISSUE THREAD

**Issue by mbabuskov** [mdqinc/SDL_GameControllerDB#784]
Hi, I'm trying to write a custom importer for this database and I have found mappings like these:

Mapping, Count
a0~: 1
a1~: 17
a2~: 3
a3~: 18
a4~: 1
a5~: 3
a6~: 1
+a0: 135
+a1: 126
+a2: 18
+a3: 20
+a4: 24
+a5: 12
-a0: 136
-a1: 127
-a2: 11
-a3: 16
-a4: 26
-a5: 4

I assume -aX means negative value on axis X, and +aX is positive value. But what are those a0~, a1~, a2~ ones?

I'm not sure if this is the right place for such information, but maybe a note explaining those could be added the README? 

Thanks.

**Comment by offalynne** [comment]
Please refer to SDL: https://github.com/libsdl-org/SDL

**Comment by mbabuskov** [comment]
Just a comment if someone finds this: 

The ~ character means that the axis is reversed, so negative values are down and right, and positive values are up and left.
