### ISSUE TITLE
Fix entries with mapping duplicates

### ISSUE THREAD

**Issue by mbabuskov** [mdqinc/SDL_GameControllerDB#785]
Hi,

I see that there's a check for duplicated controller GUIDs. It would be nice to also detect duplicate mappings for each controller, as it often means invalid configuration. For example:

Xbox Controller 03000000300f00008888000000000000 has b10 mapped to both dpleft and lefttrigger
Xbox One Controller 030000000d0f00006300000000000000 has b8 mapped to both leftstick and lefttrigger
etc.

**Comment by offalynne** [comment]
Feel free to submit a PR to the workflow python script.
