### ISSUE TITLE
Stadia controller bad read of the triggers

### ISSUE THREAD

**Issue by Torguen** [mdqinc/SDL_GameControllerDB#788]
Hi, it's possible that the analog triggers on the stadia controller are incorrectly configured.

Their values ​​are either 0 or 1, there is no intermediate value.
My tests are with godot engine
https://docs.godotengine.org/en/stable/tutorials/inputs/controllers_gamepads_joysticks.html

![Captura](https://github.com/user-attachments/assets/0c72601e-e527-4733-954e-eeca40c139bc)

**Comment by offalynne** [comment]
If you have an issue with Godot ***file your issue with Godot***
