### ISSUE TITLE
How to determine Button Layout?

### ISSUE THREAD

**Issue by snackbean** [mdqinc/SDL_GameControllerDB#802]
The [mapping guide](https://github.com/mdqinc/SDL_GameControllerDB?tab=readme-ov-file#mapping-guide) indicates how non-xbox/playstation controllers should be mapped. However, from gamecontrollerdb.txt alone, there is no way to determine which mapping was used. In other words: how do you tell what type of gamepad it is? This is critical information for various reasons:

- Game needs to know what button names and/or controller icons to use (should the Y (North) button be called Y, Δ, or X?)
- The expected confirm/cancel button depends on the controller type and region. On SNES and Pro controllers, the B (East) button (called "A") is used for confirming, whereas on Xbox controllers, it's A (South). Gamecube controllers use X (called "B") for cancel.
  - In contrast, game-action buttons like "jump" and "shoot" in most games ought to be fixed to the button position (jump=A/south, shoot=X/West)
- What gamepad image should be displayed in a control remapping screen such as [this one](https://github.com/user-attachments/assets/b3a83fed-e45d-4e68-81d7-6fa6a12f0d38).

By the way, readme should really indicate the mapping for xbox/playstation style controllers, N64 controllers, NES controllers, and what Gamecube L/R/Z and Sega Mode buttons should be mapped as. I am happy to contribute some images here in the same style, but I don't know what font the image uses.

**Comment by offalynne** [comment]
This is a community database for SDL if you have issues with SDL, take the issue up with SDL: https://github.com/libsdl-org/SDL

> *from gamecontrollerdb.txt alone, there is no way to determine which mapping was used*
Correct

> *how do you tell what type of gamepad it is*
https://wiki.libsdl.org/SDL2/SDL_GameControllerGetType

> *confirm/cancel button depends on the controller type and region*
Out of scope for the mapping db

> *By the way, readme should really indicate the mapping for xbox/playstation style controllers, N64 controllers, NES controllers, and what Gamecube L/R/Z and Sega Mode*
Did you actually look at the README? It does. Right here. https://github.com/mdqinc/SDL_GameControllerDB?tab=readme-ov-file#mapping-guide
NES and N64 are committed because the mapping is self-explanatory.

**Comment by snackbean** [comment]
I'll have to check the SDL source code, as I'm not sure how it figures out the game controller type.

NES and xbox/playstation may be fairly obvious, but N64 and Gamecube are not obvious to me. Should L be mapped to L1 or L2 for instance, and Z to R1 or R2? Are the A,B,C1-4 buttons on the N64 mapped like the sega controller?

**Comment by offalynne** [comment]
> *I'll have to check the SDL source code*

OK

> *Gamecube*

Use the README. You already linked the explanatory image, which includes very clear instructions.

> *Should L be mapped to L1 or L2 for instance, and Z to R1 or R2*

SDL mappings contain no `L1` or `R2`. I don't know how to better explain to you what `leftshoulder` and `righttrigger` mean outside the dictionary definitions of these words. If you have an actual contribution to make, and would like to include a photo or link of the device in question I can tell you how the mapping should be authored. Otherwise, please review the README again for whatever you are trying to accomplish.

**Comment by snackbean** [comment]
By the way, here's some past discussion of this issue, and this repo seems to be the Schelling point for where this information ought to be stored:

- [glfw forums](https://discourse.glfw.org/t/gamepad-mappings-and-sdl-gamecontrollerdb/1621)
- [reddit](https://old.reddit.com/r/gamedev/comments/e55zel/sdl2_how_to_get_a_humanreadable_description_of_a/)
- [A fork](https://github.com/cxong/SDL_JoystickButtonNames)(?) of SDL_GameControllerDB, which includes name and even the colour of the button.

**Comment by offalynne** [comment]
> *this repo seems to be the Schelling point for where this information ought to be stored*

No. This is a db of gamepad mappings for SDL, nothing more or less. Take your issues up with SDL or the project you linked.

**Comment by snackbean** [comment]
> Gamecube

L, R, Z are not part of the explanatory image. I would assume that Z should be mapped to `rightshoulder`, L to `lefttrigger`, and `R` to `righttrigger`. What's confusing here though is that the pro controller, also by Nintendo, calls the left shoulder button L instead, and I believe that [emudeck](https://www.emudeck.com/) goes along with this as its default dolphin configuration. So it seems there's some need for clarification I'd say.

**Comment by offalynne** [comment]
> *I would assume [..]*

Correct

> *[other projects]*

This repository has nothing to do with EmuDeck, or Dolphin, this is a DB for SDL gamepad mappings. We do not care whatever is happening downstream. Take your issues up with those projects.

> *Here are photos of the device.*

This is not what I meant. If you have data to contribute ***to this database***, feel free to open an issue sharing your work demonstrating a useful contribution, then explain whatever remains unclear to you.
