### ISSUE TITLE
[question] Hotas support soon ?

### ISSUE THREAD

**Issue by Fr-Dae** [mdqinc/SDL_GameControllerDB#806]
Hello, i'm on Lubuntu 22.04 and i have try your soft with my X52 pro hotas (logitec)
have you any plan on futur for support it ? 

thanks you, have a nice day

**Comment by Fr-Dae** [comment]
why close ?

**Comment by pengouin8140** [comment]
@offalynne hellooo he's talking to you

**Comment by offalynne** [comment]
@Fr-Dae @pengouin8140

[From the README](https://github.com/mdqinc/SDL_GameControllerDB?tab=readme-ov-file#sdl_gamecontrollerdb): A community sourced database of ***game controller mappings*** to be used with SDL2 and SDL3 Game Controller functionality

> *i have try your soft*

this is a community sourced database of game controller mappings. if you want to contribute, do so yourself.

> *X52 pro hotas (logitec)*

a HOTAS is not considered a game controller. take your issues up with SDL: https://github.com/libsdl-org
